### PR TITLE
Fixed Animation Fails To Play in Reverse.

### PR DESCRIPTION
**Pull request by dyontaistaton**
Fixed When wrapping the UseAnimation component to give it an onClick function, the animation fails to play in reverse.

### CODE REVIEW

**Comment by tuanphungcz** [comment]
Hi, thanks for this PR, but I think the fix should be in the `react-useanimations/src/utils/getEvents.js` and not in `react-useanimations/dist/utils/getEvents.js`

**Review by dyontaistaton — COMMENTED** [review]
Works Perfect!

**Comment by tuanphungcz** [comment]
yeah, so please make the fix in `react-useanimations/src/utils/getEvents.js` and make another commit

**Comment by dyontaistaton** [comment]
sorry I'm kinda new to GitHub, but the changes were in `react-useanimations/src/utils/getEvents.js`, I've sent a change proposal and I don't have access to merge this to the master so I don't know what I need to do 😅

**Comment by tuanphungcz** [comment]
ah i see, but the change request that you made is the complied code 😅 

Can you point me out where the bug was in this file? https://github.com/useAnimations/react-useanimations/blob/master/src/utils/getEvents.js

**Review by dyontaistaton — COMMENTED** [review]
This is Ready to be commited

**Pull request closed without merging**
